# Task 1

In [64]:
import numpy as np
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6]) 
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

In [65]:
'''find the common values between a and b using the function intersect1d'''
np.intersect1d(a,b)

array([2, 4])

# Task 2

In [68]:
x = np.arange(1, 16)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [67]:
'''print x in a shape of 3x5 matrix and used T to transpose'''
x.reshape(3,5).T

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

# Task 3

In [70]:
a = np.array([12, 5, 7, 15, 3, 1, 8]) 
b = np.array([14, 6, 3, 11, 19, 12, 5]) 

In [71]:
'''use setdiff1d to find the set difference of two arrays and return the sorted, 
unique values in array1 that are not in array2'''

res = np.setdiff1d(a,b)
print(res)

[ 1  7  8 15]


# Task 4

In [74]:
'''The total miles from NYC(School address-215 lexington ave. NY) to Key West is 
1552 miles in a mode of bike according to the Google Map '''
'''Record the cumulative miles until the last day of trip, then reshape in 5x7 matrix'''

trip = np.array([[50,150,210,260,320,400,400,430,450,550,600,600,650,700,760,800,850,850,900,960,1000,
                   1100,1100,1150,1200,1270,1350,1400,1480,1500,1520,1530,1540,1550,1552]])
trip.reshape(5,7)

array([[  50,  150,  210,  260,  320,  400,  400],
       [ 430,  450,  550,  600,  600,  650,  700],
       [ 760,  800,  850,  850,  900,  960, 1000],
       [1100, 1100, 1150, 1200, 1270, 1350, 1400],
       [1480, 1500, 1520, 1530, 1540, 1550, 1552]])

In [75]:
'''Since the record is cumulative miles, I calculate difference in miles to figure out daily miles'''
np.diff(trip)

array([[100,  60,  50,  60,  80,   0,  30,  20, 100,  50,   0,  50,  50,
         60,  40,  50,   0,  50,  60,  40, 100,   0,  50,  50,  70,  80,
         50,  80,  20,  20,  10,  10,  10,   2]])

# Task 5

In [55]:
import pandas
import numpy as np

# supress scientific notation
np.set_printoptions(suppress = True)

# read the data file from GitHub and convert to a NumPy ndarray object
nyc_water = pandas.read_csv('https://raw.githubusercontent.com/jtopor/DAV-5400/master/Week4/Water_Consumption_In_The_New_York_City.csv').as_matrix()

# verify you have an ndarray object
type(nyc_water)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


numpy.ndarray

### 1. What is the maximum yearly NYC consumption of water in millions of gallons per day?

In [56]:
print(nyc_water)

[[   1979.  7102100.     1512.      213. ]
 [   1980.  7071639.     1506.      213. ]
 [   1981.  7089241.     1309.      185. ]
 [   1982.  7109105.     1382.      194. ]
 [   1983.  7181224.     1424.      198. ]
 [   1984.  7234514.     1465.      203. ]
 [   1985.  7274054.     1326.      182. ]
 [   1986.  7319246.     1351.      185. ]
 [   1987.  7342476.     1447.      197. ]
 [   1988.  7353719.     1484.      202. ]
 [   1989.  7344175.     1402.      191. ]
 [   1990.  7335650.     1424.      194. ]
 [   1991.  7374501.     1469.      199. ]
 [   1992.  7428944.     1369.      184. ]
 [   1993.  7506166.     1368.5     182. ]
 [   1994.  7570458.     1357.7     179. ]
 [   1995.  7633040.     1325.7     174. ]
 [   1996.  7697812.     1297.9     169. ]
 [   1997.  7773443.     1205.5     155. ]
 [   1998.  7858259.     1219.5     155. ]
 [   1999.  7947660.     1237.2     156. ]
 [   2000.  8008278.     1240.4     155. ]
 [   2001.  8024963.5    1184.      148. ]
 [   2002. 

In [57]:
'''get the third columns from nyc_water then define it as nyc_consumption'''
nyc_consumption = nyc_water[:, [2]]
print(nyc_consumption)

[[1512. ]
 [1506. ]
 [1309. ]
 [1382. ]
 [1424. ]
 [1465. ]
 [1326. ]
 [1351. ]
 [1447. ]
 [1484. ]
 [1402. ]
 [1424. ]
 [1469. ]
 [1369. ]
 [1368.5]
 [1357.7]
 [1325.7]
 [1297.9]
 [1205.5]
 [1219.5]
 [1237.2]
 [1240.4]
 [1184. ]
 [1135.6]
 [1093.7]
 [1099.5]
 [1138. ]
 [1069. ]
 [1114. ]
 [1098. ]
 [1007.5]
 [1039. ]
 [1021. ]
 [1009.1]
 [1006.1]
 [ 996. ]
 [1009. ]
 [1002. ]
 [ 990.2]]


In [58]:
'''Find the max number among the values in nyc_consumption'''
np.amax(nyc_consumption)

1512.0

### 2. How many calendar years are represented within this data set?  NumPy's shape command is one way to find out. 

In [59]:
'''get the first columns from nyc_water then define it as years, and then find the number of the values'''
years = nyc_water.shape
years[0]

39

### 3. What is the mean and the standard deviation of the per capita daily water consumption?  

In [60]:
'''get the fourth columns from nyc_water then define it as ppdw_consumption'''
ppdw_consumption = nyc_water[:, [3]]
print(ppdw_consumption)

[[213.]
 [213.]
 [185.]
 [194.]
 [198.]
 [203.]
 [182.]
 [185.]
 [197.]
 [202.]
 [191.]
 [194.]
 [199.]
 [184.]
 [182.]
 [179.]
 [174.]
 [169.]
 [155.]
 [155.]
 [156.]
 [155.]
 [148.]
 [141.]
 [136.]
 [136.]
 [141.]
 [132.]
 [137.]
 [135.]
 [123.]
 [127.]
 [123.]
 [121.]
 [119.]
 [118.]
 [118.]
 [117.]
 [115.]]


In [78]:
'''find the mean of ppdw_consumption'''
ppdw_consumption.mean()

160.30769230769232

In [79]:
'''find the standard deviation of ppdw_consumption'''
np.std(ppdw_consumption)

31.51894330370624

### 4. What is the increase or decrease in population from year to year?  Use NumPy's `diff` function to create an array of differences and save that to a variable called "pop_diff", then print that variable to the screen.

In [80]:
'''use np.diff(x, axis=0) function and define as pop_diff'''
pop_diff = np.diff(nyc_water[:, [1],], axis=0)
print(pop_diff)

[[-30461. ]
 [ 17602. ]
 [ 19864. ]
 [ 72119. ]
 [ 53290. ]
 [ 39540. ]
 [ 45192. ]
 [ 23230. ]
 [ 11243. ]
 [ -9544. ]
 [ -8525. ]
 [ 38851. ]
 [ 54443. ]
 [ 77222. ]
 [ 64292. ]
 [ 62582. ]
 [ 64772. ]
 [ 75631. ]
 [ 84816. ]
 [ 89401. ]
 [ 60618. ]
 [ 16685.5]
 [ 16685.5]
 [ 16685.5]
 [ 16685.5]
 [ 16685.5]
 [ 16685.5]
 [ 16685.5]
 [ 16685.5]
 [ 16685.5]
 [ 16685.5]
 [108965. ]
 [ 77081. ]
 [ 61281. ]
 [ 49530. ]
 [ 44512. ]
 [ 21171. ]
 [ 85025. ]]
